"""Inert, typed tmux operation values.

This package is the pure source of truth for tmux commands: each
:class:`~.operation.Operation` renders a tmux argv, carries its result type and
metadata, and adapts raw output into a typed :class:`~.results.Result` -- all
without a live tmux server. Engines (:mod:`libtmux.experimental.engines`)
execute operations; :func:`run` / :func:`arun` bridge the two.

Everything here is experimental and not covered by the versioning policy.

Examples
--------
>>> from libtmux.experimental.ops import SplitWindow, run
>>> from libtmux.experimental.ops._types import PaneId
>>> from libtmux.experimental.engines import CommandResult
>>> SplitWindow(target=PaneId("%1"), horizontal=True).render()
('split-window', '-t', '%1', '-h', '-P', '-F', '#{pane_id}')
"""

from __future__ import annotations

from libtmux.experimental.ops._chain import OpChain
from libtmux.experimental.ops._ops import (
    BreakPane,
    CapturePane,
    ClearHistory,
    DeleteBuffer,
    DetachClient,
    DisplayMessage,
    HasSession,
    JoinPane,
    KillPane,
    KillServer,
    KillSession,
    KillWindow,
    LastPane,
    LastWindow,
    LinkWindow,
    ListClients,
    ListPanes,
    ListSessions,
    ListWindows,
    LoadBuffer,
    MovePane,
    MoveWindow,
    NewSession,
    NewWindow,
    NextWindow,
    PasteBuffer,
    PipePane,
    PreviousWindow,
    RefreshClient,
    RenameSession,
    RenameWindow,
    ResizePane,
    ResizeWindow,
    RespawnPane,
    RespawnWindow,
    RotateWindow,
    RunShell,
    SaveBuffer,
    SelectLayout,
    SelectPane,
    SelectWindow,
    SendKeys,
    SetBuffer,
    SetEnvironment,
    SetHook,
    SetOption,
    SetWindowOption,
    ShowBuffer,
    ShowOptions,
    SourceFile,
    SplitWindow,
    StartServer,
    SuspendClient,
    SwapPane,
    SwapWindow,
    SwitchClient,
    UnlinkWindow,
)
from libtmux.experimental.ops._types import (
    ClientName,
    Effects,
    IndexRef,
    NameRef,
    PaneId,
    Safety,
    Scope,
    SessionId,
    SlotRef,
    Special,
    Status,
    Target,
    WindowId,
    render_target,
)
from libtmux.experimental.ops.catalog import CatalogEntry, catalog
from libtmux.experimental.ops.exc import (
    DuplicateOperation,
    ForwardCaptureError,
    OperationError,
    TmuxCommandError,
    UnknownOperation,
    VersionUnsupported,
)
from libtmux.experimental.ops.execute import arun, run
from libtmux.experimental.ops.operation import Operation
from libtmux.experimental.ops.plan import LazyPlan, PlanResult
from libtmux.experimental.ops.planner import (
    FoldingPlanner,
    MarkedPlanner,
    Planner,
    PlanStep,
    SequentialPlanner,
)
from libtmux.experimental.ops.registry import (
    OperationRegistry,
    OpSpec,
    register,
    registry,
)
from libtmux.experimental.ops.results import (
    AckResult,
    CapturePaneResult,
    CreateResult,
    DisplayMessageResult,
    HasSessionResult,
    ListClientsResult,
    ListPanesResult,
    ListSessionsResult,
    ListWindowsResult,
    Result,
    ShowBufferResult,
    ShowOptionsResult,
    SplitWindowResult,
    status_for,
)
from libtmux.experimental.ops.serialize import (
    operation_from_dict,
    operation_to_dict,
    result_from_dict,
    result_to_dict,
    target_from_dict,
    target_to_dict,
)

__all__ = (
    "AckResult",
    "BreakPane",
    "CapturePane",
    "CapturePaneResult",
    "CatalogEntry",
    "ClearHistory",
    "ClientName",
    "CreateResult",
    "DeleteBuffer",
    "DetachClient",
    "DisplayMessage",
    "DisplayMessageResult",
    "DuplicateOperation",
    "Effects",
    "FoldingPlanner",
    "ForwardCaptureError",
    "HasSession",
    "HasSessionResult",
    "IndexRef",
    "JoinPane",
    "KillPane",
    "KillServer",
    "KillSession",
    "KillWindow",
    "LastPane",
    "LastWindow",
    "LazyPlan",
    "LinkWindow",
    "ListClients",
    "ListClientsResult",
    "ListPanes",
    "ListPanesResult",
    "ListSessions",
    "ListSessionsResult",
    "ListWindows",
    "ListWindowsResult",
    "LoadBuffer",
    "MarkedPlanner",
    "MovePane",
    "MoveWindow",
    "NameRef",
    "NewSession",
    "NewWindow",
    "NextWindow",
    "OpChain",
    "OpSpec",
    "Operation",
    "OperationError",
    "OperationRegistry",
    "PaneId",
    "PasteBuffer",
    "PipePane",
    "PlanResult",
    "PlanStep",
    "Planner",
    "PreviousWindow",
    "RefreshClient",
    "RenameSession",
    "RenameWindow",
    "ResizePane",
    "ResizeWindow",
    "RespawnPane",
    "RespawnWindow",
    "Result",
    "RotateWindow",
    "RunShell",
    "Safety",
    "SaveBuffer",
    "Scope",
    "SelectLayout",
    "SelectPane",
    "SelectWindow",
    "SendKeys",
    "SequentialPlanner",
    "SessionId",
    "SetBuffer",
    "SetEnvironment",
    "SetHook",
    "SetOption",
    "SetWindowOption",
    "ShowBuffer",
    "ShowBufferResult",
    "ShowOptions",
    "ShowOptionsResult",
    "SlotRef",
    "SourceFile",
    "Special",
    "SplitWindow",
    "SplitWindowResult",
    "StartServer",
    "Status",
    "SuspendClient",
    "SwapPane",
    "SwapWindow",
    "SwitchClient",
    "Target",
    "TmuxCommandError",
    "UnknownOperation",
    "UnlinkWindow",
    "VersionUnsupported",
    "WindowId",
    "arun",
    "catalog",
    "operation_from_dict",
    "operation_to_dict",
    "register",
    "registry",
    "render_target",
    "result_from_dict",
    "result_to_dict",
    "run",
    "status_for",
    "target_from_dict",
    "target_to_dict",
)
