"""Backwards-compatible entry point for libtmux exceptions."""

from __future__ import annotations

from libtmux.errors import (
    AdjustmentDirectionRequiresAdjustment,
    AmbiguousOption,
    BadSessionName,
    Cancelled,
    CommandError,
    InvalidOption,
    LibtmuxError,
    LibTmuxException,
    MultipleActiveWindows,
    NoActiveWindow,
    NoWindowsExist,
    OperationTimeout,
    OptionError,
    PaneAdjustmentDirectionRequiresAdjustment,
    PaneError,
    PaneNotFound,
    ProtocolError,
    RequiresDigitOrPercentage,
    TmuxCommandNotFound,
    TmuxObjectDoesNotExist,
    TmuxSessionExists,
    TransportClosed,
    UnknownColorOption,
    UnknownOption,
    VariableUnpackingError,
    VersionTooLow,
    WaitTimeout,
    WindowAdjustmentDirectionRequiresAdjustment,
    WindowError,
)

__all__ = [
    "AdjustmentDirectionRequiresAdjustment",
    "AmbiguousOption",
    "BadSessionName",
    "Cancelled",
    "CommandError",
    "InvalidOption",
    "LibTmuxException",
    "LibtmuxError",
    "MultipleActiveWindows",
    "NoActiveWindow",
    "NoWindowsExist",
    "OperationTimeout",
    "OptionError",
    "PaneAdjustmentDirectionRequiresAdjustment",
    "PaneError",
    "PaneNotFound",
    "ProtocolError",
    "RequiresDigitOrPercentage",
    "TmuxCommandNotFound",
    "TmuxObjectDoesNotExist",
    "TmuxSessionExists",
    "TransportClosed",
    "UnknownColorOption",
    "UnknownOption",
    "VariableUnpackingError",
    "VersionTooLow",
    "WaitTimeout",
    "WindowAdjustmentDirectionRequiresAdjustment",
    "WindowError",
]
